src/models/user.py
from src.utils.extensions import db, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True, nullable=False)
    password = db.Column(db.String(60), unique=True)

    def __repr__(self) -> str:
        return f"User {self.username}"

src/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from src.models.user import User
from werkzeug.security import check_password_hash

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(message='Username kiritilmadi!!!')])
    password = PasswordField('Password', validators=[DataRequired(message='Parol kiritilmadi!!!')])
    remember = BooleanField('Meni eslab qol')
    submit = SubmitField('Login')
    
    # def validate_username(self, username):
    #     user = User.query.filter_by(username=username.data).first()
        
    #     if not user:
    #         raise ValidationError('Bunday username mavjud emas!!!')
    
    def validate_password(self, password):
        username = self.data['username']
        user = User.query.filter_by(username=username).first()
        
        if user:
            checked_password = check_password_hash(user.password, password.data)
        
            if not checked_password:
                raise ValidationError('Parol noto`g`ri!!!')

src/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from src.models.user import User
from werkzeug.security import check_password_hash

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(message='Username kiritilmadi!!!')])
    password = PasswordField('Password', validators=[DataRequired(message='Parol kiritilmadi!!!')])
    remember = BooleanField('Meni eslab qol')
    submit = SubmitField('Login')
    
    # def validate_username(self, username):
    #     user = User.query.filter_by(username=username.data).first()
        
    #     if not user:
    #         raise ValidationError('Bunday username mavjud emas!!!')
    
    def validate_password(self, password):
        username = self.data['username']
        user = User.query.filter_by(username=username).first()
        
        if user:
            checked_password = check_password_hash(user.password, password.data)
        
            if not checked_password:
                raise ValidationError('Parol noto`g`ri!!!')

src/forms/upload.py
from flask_wtf import FlaskForm
from wtforms import SelectField, DateField, FileField, SubmitField
from wtforms.validators import DataRequired, ValidationError

regions = [
    {
        "name" : 'Qoraqalpog`iston Respublikasi',
        "value" : 1
    },
    {
        "name" : 'Andijon viloyati',
        "value" : 2
    },
    {
        "name" : 'Xorazm viloyati',
        "value" : 3
    },
    {
        "name" : 'Farg`ona viloyati',
        "value" : 4
    },
    {
        "name" : 'Toshkent viloyati',
        "value" : 5
    },
    {
        "name" : 'Surxondaryo viloyati',
        "value" : 6
    },
    {
        "name" : 'Sirdaryo viloyati',
        "value" : 7
    },
    {
        "name" : 'Samarqand viloyati',
        "value" : 8
    },
    {
        "name" : 'Namangan viloyati',
        "value" : 9
    },
    {
        "name" : 'Navoiy viloyati',
        "value" : 10
    },
    {
        "name" : 'Qashqadaryo viloyati',
        "value" : 11
    },
    {
        "name" : 'Jizzax viloyati',
        "value" : 12
    },
    {
        "name" : 'Buxoro viloyati',
        "value" : 13
    },
]

indexes = [
    {
        "name" : 'NDVI',
        "value" : 1
    },
    {
        "name" : 'NDMI',
        "value" : 2
    },
]

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif', 'xlsx'}

def allowed_file(filename):
        return '.' in filename and \
            filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

class UploadForm(FlaskForm):
    region = SelectField('Viloyat', validators=[DataRequired()],choices=[(reg['value'], reg['name']) for reg in regions])
    index = SelectField('Indeks', validators=[DataRequired()] , choices=[(index['value'], index['name']) for index in indexes])
    date = DateField('Kun', validators=[DataRequired()])
    file = FileField('File', validators=[DataRequired(message='File not chosen')])
    # submit = SubmitField("Ko'rish", id='preview-button')

    def validate_file(self, file):
        fileData = self.data['file']
        print(fileData.filename)
        print(allowed_file(fileData.filename))
        
        if not allowed_file(fileData.filename):
            raise ValidationError("File formati noto'g'ri!!!")

src/__init__.py
from flask import Flask
from src.utils.extensions import register_blueprints, register_extensions


def create_app(config:str):
    app = Flask(__name__)

    if config in ['dev', 'prod', 'test']:
        app.config.from_object(f"src.config.config.{config.capitalize()}Config")

    register_extensions(app)
    register_blueprints(app)

    with app.app_context():
        from src.utils.extensions import db
        from src.models.user import User

        db.create_all()
        # db.drop_all()
        
    return app

src/routes/auth.py
from flask import flash, render_template, redirect, url_for, Blueprint, request
from werkzeug.security import generate_password_hash, check_password_hash
from src.forms.login import LoginForm
from src.models.user import User
from src.utils.extensions import db
from flask_login import login_user, logout_user


auth_route = Blueprint('auth_route', __name__, url_prefix='/auth')


@auth_route.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user_query = User.query.filter_by(username=form.data['username']).first()
        if user_query:
            checked_password = check_password_hash(user_query.password, form.data['password'])
            if checked_password:
                # flash(f"{user_query.username}", 'success')
                login_user(user_query, remember=form.data['remember'])
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('base_route.home'))
            else:
                # flash(f"Parol xato!!!", 'danger')
                return redirect(url_for('auth_route.login'))
        else:
            hashed_password = generate_password_hash(form.data['password'])
            user = User(username=form.data['username'], password=hashed_password)
            login_user(user, remember=form.data['remember'])
            db.session.add(user)
            db.session.commit()
            # flash(f"{user.username}", 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('base_route.home'))
    return render_template('auth/login.html', title='Login', form=form)


@auth_route.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth_route.login'))

src/routes/home.py
from flask import render_template, Blueprint, redirect, url_for, request, jsonify
from flask_login import login_required
from src.forms.upload import UploadForm
import os
from werkzeug.utils import secure_filename

base_route = Blueprint('base_route', __name__, url_prefix='/')

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

@base_route.route('/',methods=['GET', 'POST'])
@login_required
def home():
    form = UploadForm()
    if form.validate_on_submit():
        data = form.data
        print(data)
        return jsonify('ok')
    else:
        print('error: ', form.errors)
    return render_template('index.html', form=form)

def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

src/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- jquery  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- leaflet -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
        integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="" />
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
        integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>

    <!-- styles -->
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">

    <title>NDVI</title>
</head>

<body>
    <div class="container">
        <header class="header">
            <div class="header__inner">
                {% if current_user.is_authenticated %}
                <h3>{{ current_user.username }}</h3>
                {% endif %}
                <a class="btn btn-warning btn-logout" type="button" href="{{ url_for('auth_route.logout') }}">Logout</a>
            </div>
        </header>
        <div class="content">
            <main class="main">
                <div class="main__content">
                    <div class="map__container">
                        <div id="map"></div>
                        <div class="map__form-content">
                            <div class="map__form-inner">
                                <form class="map__form" enctype='multipart/form-data' novalidate method="POST">
                                    {{ form.hidden_tag() }}
                                    <div class="mb-3 has-validation">
                                        {{ form.region.label(class='form-label') }}
                                        {{ form.region(class='form-select region-select') }}
                                    </div>
                                    <div class="mb-3">
                                        {{ form.index.label(class='form-label') }}
                                        {{ form.index(class='form-select index-select') }}
                                    </div>
                                    <div class="mb-3">
                                        {{ form.date.label(class='form-label') }}
                                        {{ form.date(class='form-select form-date', id="date") }}
                                    </div>
                                    <div class="mb-3 has-validation">
                                        {{ form.file.label(class='form-label') }}
                                        {{ form.file(class='form-select form-file', id="file", placeholder="Select file") }}
                                        <div class="file-feedback">
                                            <span class="file-feedback-txt"></span>
                                        </div>
                                    </div>
                                    {# {{ form.submit(class='btn btn-primary form__watch-btn') }} #}
                                    <button type="button" id="preview-button"
                                        class="btn btn-primary form__watch-btn">Ko'rish</button>
                                    <button type="submit" class="btn btn-success form__enter-btn">Tizimga
                                        kiritish</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    <script src="{{ url_for('static', filename='data/districts.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/map.js') }}"></script>

    <script>
        var form = document.querySelector('.map__form')
        let file_feedback = true
        let elFileInput = document.querySelector('.form-file')

        function validateFileType() {
            var selectedFile = document.querySelector('.form-file').files[0]
            let elFeedBackSpan = document.querySelector('.file-feedback-txt')
            let fileName = selectedFile?.name
            let fileFormat = null
            var allowedTypes = ['xlsx', 'zip', 'rar'];

            if (fileName) {
                fileFormat = fileName.substring(fileName.lastIndexOf(".") + 1, fileName.length)
                if (!allowedTypes.includes(fileFormat)) {
                    let txt = 'Invalid file type. Please upload a XLSX, ZIP, or RAR file.';
                    let elFileFedback = document.querySelector('.file-feedback')
                    elFeedBackSpan.textContent = txt
                    elFeedBackSpan.style.color = 'red'
                    elFileInput.classList.add('is-invalid')
                    file_feedback = true
                } else {
                    file_feedback = false
                    elFeedBackSpan.textContent = ''
                    if (elFileInput.classList.contains('is-invalid')) {
                        elFileInput.classList.remove('is-invalid')
                        elFileInput.classList.add('is-valid')
                    }
                }

            }
        }

        function classValidation(){
            let formSelect = document.querySelectorAll('.map__form select')
            let formInput = document.querySelectorAll('.map__form input')
            formSelect.forEach((element) => {
                if (element.value) {
                    element.classList.remove('is-invalid')
                    element.classList.add('is-valid')
                } else {
                    element.classList.remove('is-valid')
                    element.classList.add('is-invalid')
                }
            })

            formInput.forEach((element) => {
                if (element.value) {
                    element.classList.remove('is-invalid')
                    element.classList.add('is-valid')
                } else {
                    element.classList.remove('is-valid')
                    element.classList.add('is-invalid')
                }

            })
        }


        $(".form-file").change(function () {
            validateFileType()
        });

        $('#preview-button').on('click', () => {
            let formData = new FormData(form);
            formData.append("preview", true)
            if (form.checkValidity() && !file_feedback) {

                classValidation()

                $.ajax({
                    url: "{{ url_for('base_route.home') }}",
                    type: "POST",
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function (data) {
                        alert(data)
                    },
                    done: data => {
                        console.log(data)
                        //     let geojson = L.geoJSON(data, {
                        //         style: {
                        //             fillColor: data.features[0].properties.grid_color
                        //         }
                        //     });
                        //     console.log(data.features[0].properties.grid_color);
                        //     geojson.addTo(map);
                        //     map.fitBounds(geojson.getBounds());
                    }
                })
            } else {
                classValidation()
                validateFileType()
            }
        });
    </script>
</body>

</html>

src/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Test</h1>
</body>
</html>